{% set name = "DB12" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 014ddd87f8652fbf88ce5ad016dfdfbfc92c3845f3d294121aff1aa1a9552a5b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - db12 = db12.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-mock
    - mock
    - python {{ python_min }}
  imports:
    - db12
  commands:
    - pytest -v

about:
  home: https://github.com/DIRACGrid/DB12
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Dirac benchmark 2012 - a fast benchmark utility to estimate the power of a CPU
  description: |
    Dirac benchmark 2012 (DB12) is a fast benchmark utility used to estimate the power of a CPU.
    It is mainly used in the HEP context to forecast the duration of a given job in a WLCG worker node.
  dev_url: https://github.com/DIRACGrid/DB12

extra:
  recipe-maintainers:
    - aldbr
