{% set name = "DB12" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0ee165958836c9ef8c37766d8ccf1b3f4a0991284e0f0655564bd2b7a9de36d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - db12 = db12.__main__:main

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools-scm
  run:
    - python >=2.7

test:
  source_files:
    - tests
  requires:
    - pytest
    - mock
  imports:
    - db12
  commands:
    - pytest -v

about:
  home: https://github.com/DIRACGrid/DB12
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Dirac benchmark 2012 - a fast benchmark utility to estimate the power of a CPU
  description: |
    Dirac benchmark 2012 (DB12) is a fast benchmark utility used to estimate the power of a CPU.
    It is mainly used in the HEP context to forecast the duration of a given job in a WLCG worker node.
  dev_url: https://github.com/DIRACGrid/DB12

extra:
  recipe-maintainers:
    - aldbr
